POST http://localhost:5000/register/
Content-Type: application/json

{
    "username": "adam",
    "name": "adam",
    "password": "adam123",
    "gender": "male",
    "question": "What is your favourite food?",
    "answer": "Biryani"
}
###
POST http://localhost:5000/login/
Content-Type: application/json

{
    "username": "adam",
    "password": "adam123"
}
###
GET http://localhost:5000/forgot/question
Content-Type: application/json

{
    "username": "adam"
}
###
PUT http://localhost:5000/forgot/reset
Content-Type: application/json

{
    "username": "adam",
    "password": "adam456"
}
###
###
GET http://localhost:5000/
Content-Type: application/json
###
GET http://localhost:5000/home/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW0iLCJpYXQiOjE2OTE3NDMyODd9.u95PkuuYow8EZUWWQzDvw9C5fbAVRbJal6KkOMkqVj4
###
GET http://localhost:5000/packages/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW0iLCJpYXQiOjE2OTE3NDMyODd9.u95PkuuYow8EZUWWQzDvw9C5fbAVRbJal6KkOMkqVj4
###
GET http://localhost:5000/packages/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW0iLCJpYXQiOjE2OTE3NDMyODd9.u95PkuuYow8EZUWWQzDvw9C5fbAVRbJal6KkOMkqVj4
###
POST http://localhost:5000/packages/1/feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW0iLCJpYXQiOjE2OTE3NDMyODd9.u95PkuuYow8EZUWWQzDvw9C5fbAVRbJal6KkOMkqVj4

{
    "rating": 4.5,
    "review": "Super journey to andaman"
}
###
POST http://localhost:5000/bookings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW0iLCJpYXQiOjE2OTE3NDMyODd9.u95PkuuYow8EZUWWQzDvw9C5fbAVRbJal6KkOMkqVj4

{
    "location": "Andaman",
    "price": 12000,
    "persons": 2,
    "date": "11-08-2023"
}
###
GET http://localhost:5000/bookings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW0iLCJpYXQiOjE2OTE3NDMyODd9.u95PkuuYow8EZUWWQzDvw9C5fbAVRbJal6KkOMkqVj4
