GET http://localhost:5000/
Content-Type: application/json
###
POST http://localhost:5000/register/
Content-Type: application/json

{
    "username": "adam",
    "name": "adam",
    "password": "adam123",
    "gender": "male"
}
###
POST http://localhost:5000/login/
Content-Type: application/json

{
    "username": "adam",
    "password": "adam123"
}